name: Fetch and Transform Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Every Day

jobs:
  fetch_and_transform:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Fetch data using curl
      - name: Fetch Data
        run: |
          curl 'https://api.airtable.com/v0/appOcPmkuwy3wxipe/Banks' \
            --header 'Authorization: Bearer ${{ secrets.NIGERIAN_BANKS_AIRTABLES }}' > data.json
          date > last-updated.txt

      # Step 3: Transform Data
      - name: Transform Data
        run: |
          # Transform the fetched data to the desired format and add enclosing brackets
          echo '[' > transformed_data.json
          cat data.json | jq '.records[].fields' >> transformed_data.json
          echo ']' >> transformed_data.json

      # Step 4: Commit and Push Changes
      - name: Commit and Push Data
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add transformed_data.json
          git commit -m "Transform and Fetch New Data"
          git push
