name: Transform JSON Data

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  transform_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Fetch and Transform JSON Data
        run: |
          const fetch = require('node-fetch');
          const fs = require('fs');

          const airtableEndpoint = 'YOUR_AIRTABLE_ENDPOINT_URL';
          const transformedDataFile = 'transformed_data.json';
          const authToken = 'YOUR_AUTH_TOKEN'; // Replace with your actual token

          const fetchAirtableData = async () => {
            try {
              const response = await fetch(airtableEndpoint, {
                headers: {
                  Authorization: `Bearer ${authToken}`
                }
              });
              const data = await response.json();
              return data;
            } catch (error) {
              console.error('Error fetching data from Airtable:', error);
              return null;
            }
          };

          const transformData = (originalData) => {
            const transformedData = originalData.records.map(record => record.fields);
            return transformedData;
          };

          (async () => {
            const originalData = await fetchAirtableData();
            if (originalData) {
              const transformedData = transformData(originalData);
              fs.writeFileSync(transformedDataFile, JSON.stringify(transformedData, null, 4));
              console.log('Data transformation complete.');
              
              // Commit and push changes
              const cp = require('child_process');
              cp.execSync('git config --global user.email "github-actions-bot@example.com"');
              cp.execSync('git config --global user.name "GitHub Actions Bot"');
              cp.execSync('git add transformed_data.json');
              cp.execSync('git commit -m "Update transformed data"');
              cp.execSync('git push');
            }
          })();
